[package]
name = "comp"
version = "0.1.0"
authors = ["hkdnet <satoko.itse@gmail.com>"]
edition = "2018"

# dependencies added to new project
[dependencies]
proconio = "*"
num-bigint = "0.2.6"
num-traits = "0.2.11"
num-integer = "0.1.42"

[profile.release]
lto = true
panic = 'abort'
